### PR TITLE
Lazy seq paging

### PR DESCRIPTION
**Pull request by mpisanko**
results->map function could use parse function to gain the same lazy querying behaviour if it accepted query parameter.

### CODE REVIEW

**Comment by mpisanko** [comment]
Hey Paul, any ideas / feedback about this PR?

**Comment by mpisanko** [comment]
@pingles @sdawara - any update / feedback on this?

**Comment by pingles** [comment]
Changes work for me- thanks for all your hard work! Would you mind squashing them together so there's a single commit to merge into master please?

Also- please leave the version number change out- given the API of the `execute` fn is changing it should probably mean incrementing at least a minor version not just point.

**Comment by mpisanko** [comment]
hey @pingles - will close this PR and submit a new one.
the commit history on this branch is a dog's breakfast.

**Comment by pingles** [comment]
Haha, thank you :)

**Comment by mpisanko** [comment]
The same thing - just tidy:
https://github.com/uswitch/analytij/pull/10

**Pull request closed without merging**
