### PR TITLE
Page handler

### PR DESCRIPTION
**Pull request by mpisanko**

### CODE REVIEW

**Comment by pingles** [comment]
Hi,

Thanks for your commits. I'm not so sure about the extract function- is there a reason you've added a handler, rather than just iterating over the sequence of results that execute returns?

**Comment by mpisanko** [comment]
The main reason is OOME when you get a really large response back. And being able to do whatever you need to do with the pages. I should probably structure it differently (so that the handler does not have to return a vector - it is not obvious that/why it should).

**Comment by mpisanko** [comment]
Another (a better?) solution might be a lazy sequence of results.

**Comment by pingles** [comment]
Yeah- I think I'd definitely prefer a lazy paginating sequence than passing
a handler in.

**Comment by pingles** [comment]
I think changing the way the code works to generate a lazy sequence from the paginated results would be great to address the OOME.

For now I'll close this and then revisit later.

Thanks again.

**Pull request closed without merging**
